services:
  - type: web
    name: discord-trading-bot
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r dependencies.txt"
    startCommand: "python main.py"
    plan: free
    region: oregon
    runtime: python-3.11.0
    healthCheckPath: /health